resourcestring                                     {deutsch}

  rsAppName='Yuneec Batterie Check';
  capOpenDialog='FlightLog Datei öffnen...';
  capOpen='&Telemetrie öffnen';
  hntOpen='FlightLog Datei zum Auswerten öffnen';
  capFile='&Datei';
  capSave='&Speichern';
  capClose='&Beenden';
  hntClose='Programm beenden';
  capHelp='&Hilfe';
  capHomepage='&Meine Homepage';
  capAbout='&Über das Programm';
  capBatt='Umrechnungsregel';
  hntBatt='Regel für Umrechnen der LiPo-Spannung in Restkapazität';
  capVolt='Spannung';
  capCap='Restkapazität';
  hntCap='Restkapazität auch anzeigen';
  rsManual='readme_de.txt';

  rsVType= 'Kopter Typ:       ';
  rsZeit=  'Beginnzeit:       ';
  rsEZeit= 'Endezeit:         ';
  rsCells= 'Anzahl Zellen:    ';
  rsFDur=  'Flugzeit etwa:    ';
  rsVmin=  'Spannungsminimum: ';
  rsQuali= 'Batteriezustand:  ';
  rsTief=  '                  Achtung: Unterspannung!';
  rsHVLiPo='                  HV-LiPo';
  rsVW1=   '                  Voltage warning 1 ausgegeben';
  rsVW2=   '                  Voltage warning 2 ausgegeben';
  rsBwert1='Gut';
  rsBwert2='Beobachten';
  rsBwert3='Bedenklich';
  rsSchrott='Schrott!';

  rsFileSize='Datei zu klein.';
  rsNotCharged='Batterie nicht genug geladen.';
  rsNoStart='Keine ausreichende Entladung entdeckt.';
  rsNoFlight='Kein Flug erkannt.';
  rsNoData='Unzureichende Daten.';
  rsNoAnal='Keine Auswertung möglich.';

  rsOldFW='H920 (alte Firmware)';
  rsSavedTo='Gespeichert unter: ';
  rsSegm='Segment';

  errUnknown='Unbekanntes Dateiformat.';
  errInvalid='ungültiger Wert';

