resourcestring                                     {english}

  rsAppName='Yuneec battery check';
  capOpenDialog='Open FlightLog file...';
  capOpen='&Open telemetry';
  hntOpen='Open a telemetry file from flight log to check battery.';
  capFile='&File';
  capSave='&Save';
  capClose='&Close';
  hntClose='Close application';
  capHelp='&Help';
  capHomepage='&My homepage';
  capAbout='&About';
  capBatt='Conversion rule';
  hntBatt='Rule to convert battery voltage to remaining capacity';
  capVolt='Voltage';
  capCap='Remaining capacity';
  hntCap='Show also remaining capacity in chart';
  rsManual='readme_en.txt';

  rsVType= 'Vehicle type:    ';
  rsZeit=  'Begin time:      ';
  rsEZeit= 'End time:        ';
  rsCells= 'Number cells:    ';
  rsFDur=  'Flight time:     ';
  rsVmin=  'Minimum voltage: ';
  rsQuali= 'Battery quality: ';
  rsTief=  '                 Note: Voltage drop!';
  rsHVLiPo='                 HV-LiPo';
  rsVW1=   '                 Voltage warning 1 raised';
  rsVW2=   '                 Voltage warning 2 raised';
  rsBwert1='Good';
  rsBwert2='Needs observation';
  rsBwert3='Critical';
  rsSchrott='Waste!';
  
  rsFileSize='File too small.';
  rsNotCharged='battery not charged enough.';
  rsNoStart='Discharge load not detected.';
  rsNoFlight='No flight detected.';
  rsNoData='Insufficient data.';
  rsNoAnal='Analysis not possible.';
  rsOldFW='H920 (old firmware)';
  rsSavedTo='Saved to: ';
  rsSegm='Segment';

  errUnknown='Unknown file format.';
  errInvalid='invalid value';

