
{.$I batterycheck_dt.inc}
{$I batterycheck_en.inc}

resourcestring                                     {Länderneutral}

  appvers='V0.2 2021-04-22';

  tab1=' ';
  tab2='  ';

  YlegacyID=',fsk_rssi,voltage,current,';
  HPlusID=  ',fskRssi,voltage,current,';
  BreezeID1='YC';
  BreezeID2='UTC,TimeStamp,flightMode,distance,';
  H920ID1=  ',1,';
  H920ID2=  ',16,';
  H920ID3=  ',-';
  H501ID=   'Time;frames;Lat;Lon;Elev;';

  fmodeID='f_mode';


